language: python
services:
  - xvfb
addons:
  firefox: "62.0.3"
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - "2.7"
matrix:
  fast_finish: true
python: 2.7
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout buildout:download-cache=downloads
before_script:
  - export DISPLAY=:99.0
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver && tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls
