language: python
addons:
  firefox: "52.0.2"
sudo: true
cache:
  directories:
    - eggs
    - downloads
python: 2.7
install:
  - pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout buildout:download-cache=downloads
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls==0.5
  - coveralls
