language: python
services:
  - xvfb
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - "2.7"
matrix:
  fast_finish: true
python: 2.7
before_install:
  - sudo apt-get install -y firefox-geckodriver
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout buildout:download-cache=downloads
before_script:
  - export DISPLAY=:99.0
  - firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls
